#############################################################################
# Makefile for building: bin/projet_lifap4
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  projet_lifap4.pro
# Template: app
# Command: /home/florian/Qt/5.14.1/gcc_64/bin/qmake -o Makefile projet_lifap4.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/home/florian/Qt/5.14.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/florian/Qt/5.14.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/florian/Qt/5.14.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/florian/Qt/5.14.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = projet_lifap41.0.0
DISTDIR = /home/florian/Dropbox/Licence/L2/S4/LIFAP4/projet_lifap4/obj/projet_lifap41.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/usr/lib -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Map.cpp \
		src/Button.cpp \
		src/Game.cpp \
		src/Inventory.cpp \
		src/Menu.cpp \
		src/Rectangle.cpp \
		src/Image.cpp \
		src/SDL_Game.cpp \
		src/main.cpp \
		src/Character.cpp \
		src/Player.cpp \
		src/Enemy.cpp \
		src/Object.cpp 
OBJECTS       = obj/Map.o \
		obj/Button.o \
		obj/Game.o \
		obj/Inventory.o \
		obj/Menu.o \
		obj/Rectangle.o \
		obj/Image.o \
		obj/SDL_Game.o \
		obj/main.o \
		obj/Character.o \
		obj/Player.o \
		obj/Enemy.o \
		obj/Object.o
DIST          = /home/florian/Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/unix.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/linux.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/qconfig.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qml_debug.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/warn_on.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/lex.prf \
		projet_lifap4.pro src/Map.h \
		src/Inventory.h \
		src/common.h \
		src/Button.h \
		src/Game.h \
		src/Image.h \
		src/Menu.h \
		src/Rectangle.h \
		src/SDL_Game.h \
		src/Vec2.h \
		src/Character.h \
		src/Player.h \
		src/Enemy.h \
		src/Object.h src/Map.cpp \
		src/Button.cpp \
		src/Game.cpp \
		src/Inventory.cpp \
		src/Menu.cpp \
		src/Rectangle.cpp \
		src/Image.cpp \
		src/SDL_Game.cpp \
		src/main.cpp \
		src/Character.cpp \
		src/Player.cpp \
		src/Enemy.cpp \
		src/Object.cpp
QMAKE_TARGET  = projet_lifap4
DESTDIR       = bin/
TARGET        = bin/projet_lifap4


first: all
####### Build rules

bin/projet_lifap4:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: projet_lifap4.pro /home/florian/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf /home/florian/Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/unix.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/linux.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/qconfig.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qml_debug.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/warn_on.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/lex.prf \
		projet_lifap4.pro
	$(QMAKE) -o Makefile projet_lifap4.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/unix.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/linux.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/qconfig.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qml_debug.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/warn_on.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf:
/home/florian/Qt/5.14.1/gcc_64/mkspecs/features/lex.prf:
projet_lifap4.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile projet_lifap4.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile bin/projet_lifap4

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/Map.o: src/Map.cpp src/Map.h \
		src/Rectangle.h \
		src/Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Map.o src/Map.cpp

obj/Button.o: src/Button.cpp src/Button.h \
		src/Rectangle.h \
		src/Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Button.o src/Button.cpp

obj/Game.o: src/Game.cpp src/Game.h \
		src/Menu.h \
		src/Button.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/common.h \
		src/Player.h \
		src/Character.h \
		src/Image.h \
		src/Enemy.h \
		src/Object.h \
		src/Map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Game.o src/Game.cpp

obj/Inventory.o: src/Inventory.cpp src/Inventory.h \
		src/Menu.h \
		src/Button.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Inventory.o src/Inventory.cpp

obj/Menu.o: src/Menu.cpp src/Menu.h \
		src/Button.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Menu.o src/Menu.cpp

obj/Rectangle.o: src/Rectangle.cpp src/Rectangle.h \
		src/Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Rectangle.o src/Rectangle.cpp

obj/Image.o: src/Image.cpp src/Image.h \
		src/Rectangle.h \
		src/Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Image.o src/Image.cpp

obj/SDL_Game.o: src/SDL_Game.cpp src/SDL_Game.h \
		src/Game.h \
		src/Menu.h \
		src/Button.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/common.h \
		src/Player.h \
		src/Character.h \
		src/Image.h \
		src/Enemy.h \
		src/Object.h \
		src/Map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/SDL_Game.o src/SDL_Game.cpp

obj/main.o: src/main.cpp src/SDL_Game.h \
		src/Game.h \
		src/Menu.h \
		src/Button.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/common.h \
		src/Player.h \
		src/Character.h \
		src/Image.h \
		src/Enemy.h \
		src/Object.h \
		src/Map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/Character.o: src/Character.cpp src/Character.h \
		src/Image.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Character.o src/Character.cpp

obj/Player.o: src/Player.cpp src/Player.h \
		src/Character.h \
		src/Image.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/Enemy.h \
		src/Object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Player.o src/Player.cpp

obj/Enemy.o: src/Enemy.cpp src/Enemy.h \
		src/Character.h \
		src/Image.h \
		src/Rectangle.h \
		src/Vec2.h \
		src/Player.h \
		src/Object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Enemy.o src/Enemy.cpp

obj/Object.o: src/Object.cpp src/Object.h \
		src/Image.h \
		src/Rectangle.h \
		src/Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Object.o src/Object.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

